// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GiftrMVP_Backend.Migrations
{
    [DbContext(typeof(GiftrDbContext))]
    [Migration("20260702222305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gift", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("gift_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GiftId"));

                    b.Property<bool>("Given")
                        .HasColumnType("boolean")
                        .HasColumnName("given");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<int?>("RecipientId")
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("GiftId")
                        .HasName("pk_gifts");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_gifts_profile_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_gifts_recipient_id");

                    b.ToTable("gifts", (string)null);
                });

            modelBuilder.Entity("ImageAsset", b =>
                {
                    b.Property<int>("ImageAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_asset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageAssetId"));

                    b.Property<int?>("GiftId")
                        .HasColumnType("integer")
                        .HasColumnName("gift_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("ImageKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("image_key");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("ImageAssetId")
                        .HasName("pk_image_assets");

                    b.HasIndex("GiftId")
                        .IsUnique()
                        .HasDatabaseName("ix_image_assets_gift_id");

                    b.ToTable("image_assets", (string)null);
                });

            modelBuilder.Entity("Profile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProfileId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("ProfileId")
                        .HasName("pk_profiles");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_email");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Recipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("recipient_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.HasKey("RecipientId")
                        .HasName("pk_recipients");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_recipients_profile_id");

                    b.ToTable("recipients", (string)null);
                });

            modelBuilder.Entity("Gift", b =>
                {
                    b.HasOne("Profile", "Profile")
                        .WithMany("Gifts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gifts_profiles_profile_id");

                    b.HasOne("Recipient", "Recipient")
                        .WithMany("Gifts")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_gifts_recipients_recipient_id");

                    b.Navigation("Profile");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("ImageAsset", b =>
                {
                    b.HasOne("Gift", "Gift")
                        .WithOne("ImageAsset")
                        .HasForeignKey("ImageAsset", "GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_image_assets_gifts_gift_id");

                    b.Navigation("Gift");
                });

            modelBuilder.Entity("Recipient", b =>
                {
                    b.HasOne("Profile", "Profile")
                        .WithMany("Recipients")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipients_profiles_profile_id");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Gift", b =>
                {
                    b.Navigation("ImageAsset");
                });

            modelBuilder.Entity("Profile", b =>
                {
                    b.Navigation("Gifts");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("Recipient", b =>
                {
                    b.Navigation("Gifts");
                });
#pragma warning restore 612, 618
        }
    }
}
